---
title: "p8105_hw2_ml4198"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
```

## Problem 1

Mr. Trashwheel datasheet

```{r}
mr_trashwheel = 
  readxl::read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = 1, range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  ) 
```

2017 Precipitation sheet

```{r}
precipitation_2017 = 
  readxl::read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

2018 Precipitation sheet

```{r}
precipitation_2018 = 
  readxl::read_excel("./Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = 2018) %>% 
  relocate(year)
```

Join precipitation sheets

```{r}
precipitation_data = 
  full_join(precipitation_2017, precipitation_2018)
```


